[phases.setup]
nixPkgs = ['...', 'python3']

[phases.install]
cmds = [
    'rm -f package-lock.json',
    'npm install --legacy-peer-deps',
    'composer install --optimize-autoloader --no-dev'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8080}'
